// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpuyZw2KzbaO3uMKc_IVGU9I1yr8Jw2ts',
    appId: '1:220778835397:web:539d0b8d4ed99b55c82fac',
    messagingSenderId: '220778835397',
    projectId: 'local-shop-9b84b',
    authDomain: 'local-shop-9b84b.firebaseapp.com',
    storageBucket: 'local-shop-9b84b.appspot.com',
    measurementId: 'G-LHNS5XSQDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3St-gxmuFat4lT60dTkTZRHWkeQ4dbH8',
    appId: '1:220778835397:android:39debe268243970ac82fac',
    messagingSenderId: '220778835397',
    projectId: 'local-shop-9b84b',
    storageBucket: 'local-shop-9b84b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfO5N2vE6ho8Y4pMUfose6p4r3Cgkz4k',
    appId: '1:220778835397:ios:e3c18429621f6414c82fac',
    messagingSenderId: '220778835397',
    projectId: 'local-shop-9b84b',
    storageBucket: 'local-shop-9b84b.appspot.com',
    iosBundleId: 'com.example.localShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfO5N2vE6ho8Y4pMUfose6p4r3Cgkz4k',
    appId: '1:220778835397:ios:2a1cd3d4260fa2d5c82fac',
    messagingSenderId: '220778835397',
    projectId: 'local-shop-9b84b',
    storageBucket: 'local-shop-9b84b.appspot.com',
    iosBundleId: 'com.example.localShop.RunnerTests',
  );
}
